# Generated by Django 3.2.4 on 2021-06-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_alter_route_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
