# Generated by Django 3.2.4 on 2021-06-11 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0003_auto_20210610_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waypoint',
            name='coordinate0',
        ),
        migrations.RemoveField(
            model_name='waypoint',
            name='coordinate1',
        ),
    ]
