# Generated by Django 3.2.4 on 2021-06-11 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0004_auto_20210611_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='waypoint',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('name', models.TextField()),
                ('waypoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.waypoint')),
            ],
        ),
    ]
